//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratornie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uchetnaya
    {
        public int Nomer_zapisi { get; set; }
        public int Tabelnyi_nomer { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<decimal> Oklad { get; set; }
        public Nullable<decimal> Procent_oplaty { get; set; }
    
        public virtual Spravochnaya Spravochnaya { get; set; }
    }
}
